### ISSUE TITLE
Serveronly mode error: EADDRINUS

### ISSUE THREAD

**Issue by lcao0411** [Veldrovive/MMM-Voice-Commands#9]
Hi, I'm having trouble running this using "node serveronly" under /home/pi/MagicMirror/. It gives me {Error: listen EADDRINUSE: address already in use 0.0.0.0:8080 ...} I tried "kill -9 PID" but no luck. May I have your help? Much much thanks!

**Comment by Veldrovive** [comment]
Ah, this isn't really the correct place for this issue, but since it is tangentially important to this module, I'll try to help.

That error means that you have a server that is already using `localhost:8080`. There are a couple of ways to solve this.
1. Restart your computer: This will stop any running processes including your old node instances
2. pkill node/pkill nodejs: These are similar to the one you tried, but uses a broader stroke than the pinpoint `pkill PID`. The reason that didn't work is probably that you had the `PID` incorrect.
3. Change the port: An old instance is using `localhost:8080`, but if you change the port to something else like `localhost:8081`, it should work fine.

I hope that helped.

**Comment by lcao0411** [comment]
Hi, Thank you for trying to help! 

1. This issue happens when I restart the pi; not sure if it's because the current setting - every time I restart the pi magicmirror screen automatically pop up. 

2. I killed all PID found by running " ps aux | grep node"

3. I also just changed port ID in config.js to be 8081, and rerun "node serveronly" under /home/pi/MagicMirror

1, 2, and 3 all gave me EADDRINUSE error. My config file, after adding MMM-Voice_Commands code, produces a whole black mirror screen showing nothing (It shows contents as it's supposed to only if I set useHttps: false in config.js). I just minimized the black screen before running  "cd ./MagicMirror/" and "node serveronly"

**Comment by Veldrovive** [comment]
1. If the magic mirror screen pops up when you restart the pi, that means that you have set up an autostart script. Are you using pm2? Try running `pm2 list` to see what scripts you have and then use `pm2 show ID` to get information about where each is running from.
2. If the magic mirror screen that pops up on startup does not go away when you do this, then not all of the node processes are being destroyed. It's likely that whatever autostart you are using changes the process name to something besides `node`.
3. It is not unlikely that there is another process running on `localhost:8081`. Have you tried a large variety of ports? It all of them are taken then that suggests a very strange problem and one that I am not qualified to solve.

The reason that you just get a blank screen when using https with electron is that the path to the key is not being set correctly. This doesn't matter though since using https with electron doesn't change anything.
Minimizing the black screen does not get it to release the address which is why the process needs to be located and ended for you to reuse the port for another process.

**Comment by lcao0411** [comment]
1. I assume that I use pm2 (sorry I'm kindf new) because pm2 commands works. It shows 3 ids: id 0 and id 1 are both config.js with different pid path; id 2 is mm.sh.

2.I basically followed the MagicMirror installation instruction, and chose yes to the two setup questions. Questions about if auto start magicmirror. If not node what else would you suggest trying?

Black-screen: I followed your instruction on a different post to get the key. How do I know if it's correct. I thought I'm not supposed to use https with electron but use browser? One more silly question, how can I end the process then?

Regards
